import type { PresetDefinition, RunSettings } from './types';

export const DEFAULT_SETTINGS: RunSettings = {
  instrumentId: 'flute',
  soundProfile: 'general-midi',
  presetId: 'neutral',
  keyRoot: 0,
  scaleId: 'major',
  tempo: 140,
  timeSignatureNumerator: 4,
  timeSignatureDenominator: 4,
  phraseLength: 1,
  phraseLengthUnit: 'bars',
  notationPitchMode: 'written',
  dynamicContourMode: 'natural',
  subdivision: 16,
  tuplet: 1,
  direction: 'ascending',
  startNote: 60,
  endNote: 84,
  lowestNote: 60,
  highestNote: 84,
  gatePercent: 82,
  midiChannel: 1,
  programChangeEnabled: false,
  programNumber: 74,
  velocity: {
    base: 78,
    min: 54,
    max: 108,
    peakPosition: 55,
    curve: 's-curve',
  },
  ccLaneA: {
    enabled: false,
    controller: 1,
    min: 32,
    max: 92,
    peakPosition: 55,
    curve: 's-curve',
  },
  ccLaneB: {
    enabled: false,
    controller: 11,
    min: 64,
    max: 108,
    peakPosition: 60,
    curve: 'linear',
  },
  ccDensityPerBeat: 4,
};

export const PRESETS: PresetDefinition[] = [
  {
    id: 'neutral',
    name: 'Neutral',
    soundProfile: 'general-midi',
    patch: {
      soundProfile: 'general-midi',
      gatePercent: 82,
      velocity: {
        base: 78,
        min: 54,
        max: 108,
        peakPosition: 55,
        curve: 's-curve',
      },
      ccLaneA: {
        enabled: false,
        controller: 1,
        min: 32,
        max: 92,
        peakPosition: 55,
        curve: 's-curve',
      },
      ccLaneB: {
        enabled: false,
        controller: 11,
        min: 64,
        max: 108,
        peakPosition: 60,
        curve: 'linear',
      },
    },
  },
  {
    id: 'bbcso-short-run',
    name: 'BBCSO Short Run',
    soundProfile: 'bbcso-pro',
    patch: {
      soundProfile: 'bbcso-pro',
      gatePercent: 58,
      velocity: {
        base: 92,
        min: 58,
        max: 122,
        peakPosition: 54,
        curve: 'ease-out',
      },
      ccLaneA: {
        enabled: false,
        controller: 1,
        min: 24,
        max: 58,
        peakPosition: 54,
        curve: 'linear',
      },
      ccLaneB: {
        enabled: true,
        controller: 11,
        min: 66,
        max: 112,
        peakPosition: 58,
        curve: 's-curve',
      },
    },
  },
  {
    id: 'bbcso-legato-fast-run',
    name: 'BBCSO Legato/Fast Run',
    soundProfile: 'bbcso-pro',
    patch: {
      soundProfile: 'bbcso-pro',
      gatePercent: 104,
      velocity: {
        base: 72,
        min: 66,
        max: 82,
        peakPosition: 55,
        curve: 'linear',
      },
      ccLaneA: {
        enabled: true,
        controller: 1,
        min: 28,
        max: 116,
        peakPosition: 56,
        curve: 's-curve',
      },
      ccLaneB: {
        enabled: true,
        controller: 11,
        min: 72,
        max: 104,
        peakPosition: 60,
        curve: 'ease-out',
      },
    },
  },
];
